// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBJfc2StqTkkPUBeK5cBZvrw0OIUqVYY',
    appId: '1:884836591001:web:d59ef7bd8842204c685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    authDomain: 'safechat-7f27d.firebaseapp.com',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
    measurementId: 'G-DWLJSTPTKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUgzmDMxZNlZ-nE9zqtJVjZ7FuhRS7Muw',
    appId: '1:884836591001:android:b11589968a636b33685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYtwudTQ1en5p59yQBGaKLRiWFBuT2gMk',
    appId: '1:884836591001:ios:b4e00c274e34a22c685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
    androidClientId: '884836591001-r690nja9mouuvobakvnc68pk71l7o3up.apps.googleusercontent.com',
    iosClientId: '884836591001-8pnl6lhlrhv2qitbq34jr07pe4je0hha.apps.googleusercontent.com',
    iosBundleId: 'com.example.safechatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYtwudTQ1en5p59yQBGaKLRiWFBuT2gMk',
    appId: '1:884836591001:ios:b4e00c274e34a22c685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
    androidClientId: '884836591001-r690nja9mouuvobakvnc68pk71l7o3up.apps.googleusercontent.com',
    iosClientId: '884836591001-8pnl6lhlrhv2qitbq34jr07pe4je0hha.apps.googleusercontent.com',
    iosBundleId: 'com.example.safechatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiBJfc2StqTkkPUBeK5cBZvrw0OIUqVYY',
    appId: '1:884836591001:web:ac7f922551127245685f08',
    messagingSenderId: '884836591001',
    projectId: 'safechat-7f27d',
    authDomain: 'safechat-7f27d.firebaseapp.com',
    storageBucket: 'safechat-7f27d.firebasestorage.app',
    measurementId: 'G-GMMVX8FPQC',
  );

}